credentials:
  usernames:
    solegn:
      email: solegn@gmail.com
      name: solegn
      password: '$2b$12$dFOCbujmmYNafHWjyKF9UurrWIwwvUdgmrIXG7KQsZeHcg05yaMPe' # hash s459939on -> hashed_passwords = stauth.Hasher(['s459939on', '123456']).generate()
cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - test@test.test