[theme]
primaryColor='rgba(18,97,149, 1)'
backgroundColor='rgba(255, 255, 255, 0.2)'
# secondaryBackgroundColor='rgba(240, 240, 240, 0.9)'
secondaryBackgroundColor='rgba(196,221,235, 0.9)'
textColor='rgba(0, 0, 0, 0.9)'
# font="sans serif"